### ISSUE TITLE
My menu doesn't appear

### ISSUE THREAD

**Issue by memlolmem** [DRE2N/HolographicMenus#25]
i have a menu in plugins/holographicmenus/menus named menu.yml, and when i type /hm menu, it doesn't show up.
Here's the config:
```
type: PRIVATE

followingOnMove: true

menuPages:
  1:
    buttons:
      1:
	label: "●Tp"
	type: BUTTON
	sound: ui.button.click
	command: "say tp" 
        closeMenu: true
	x: 0.0
	y: 0.2
     2:
	label: "●guild"
	type: BUTTON
	sound: ui.button.click
	command: "say guild"
        closeMenu: true
	x: 0.0
	y: 0.0
     3:
	label: "●friends"
	type: BUTTON
	sound: ui.button.click
	command: "say friends"
        closeMenu: true
	x: 0.0
	y: -0.2
  1:
    buttons:
      1:
         label: "hehe"
         type: TITLE
         x: 0.0
         y: 0.0

staticButtons:
  1:
    label: "X"
    type: BUTTON
    sound: ui.button.click
    closeMenu: true
    x: 0.0
    y: -0.4

distance: 1.75

rotationTolerance: 25
```
